Bacsan/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bac_app.urls'))
]

bac_app/urls.py
from django.urls import path
from . import views

app_name = 'bac_app'



urlpatterns = [
    path('',views.home,name='home'),
    path('register/',views.register,name='register'),
    path('login/',views.login_requeset,name='login'),
    path('logout/',views.logout_request,name='logout'),
]

bac_app/models.py
from operator import mod
from django.db import models
from djmoney.models.fields import MoneyField
# Create your models here.

class FromFactry(models.Model):
    item = models.CharField('item', max_length=100)
    qty = models.IntegerField('qty')
    cost_price= MoneyField(max_digits=10,decimal_places=2,default_currency='USD')
    in_date = models.DateField()
    
    
    
    def __str__(self):
        return self.item
    
    
class Sales(models.Model):
    date = models.DateField()
    tiem = models.ForeignKey(FromFactry, on_delete=models.CASCADE)  
    qty =  models.ImageField('qty')
    price = MoneyField(max_digits=10,decimal_places=2,default_currency='USD')
  
    
    
    def __str__(self):
        return self.date
    
    
class StoreIn(models.Model):
    item = models.ForeignKey(FromFactry,on_delete=models.CASCADE)
    qty = models.IntegerField()
    total= models.IntegerField()
    
    def __str__(self):
        return self.total      
    
    
    

bac_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    
    class Meta:
        model = User
        fields = ("username", "email", "password1","password2")
        
        
        
    def __str__(self):
        return self.username    
        
        
        
        

bac_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout , authenticate
from .forms import RegisterForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
# Create your views here.



def home(request):
    return render(request,'bac_app/home.html')


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user= form.save(commit=True)
            login(request, user)
            messages.success(request,'your in ')
            return redirect('bac_app:home')
        else:
            messages.error(request,'something gos wrong')
    form = RegisterForm()            
    return render(request,'bac_app/register.html',{
        'register_form':form,
        'messages':messages,
    })


def login_requeset(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username= username, password= password)
            if user is not None:
                login(request, user)
                messages.success(request,f'wellcome{username}')
                return redirect ('bac_app:home')
            else:
                messages.info(request,'something gos wrong')
    form = AuthenticationForm()            
    return render(request,'bac_app/login.html',{
        'login_form': form,
    })



def logout_request(request):
    logout(request)
    return redirect('bac_app:home')

templates/bac_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bac_app/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bac_app/css/master.css' %}">
    <title>Document</title>
</head>
<body>
    <div>
        <nav class="navbar navbar-dark bg-dark fixed-top">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Wecome To BacSan {{messages|safe}}</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                <div class="offcanvas-header">
                  <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Dark offcanvas</h5>
                  <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'bac_app:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                      <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        {% if user.is_authenticated %}
                        <li><a class="nav-link" href="{% url 'bac_app:logout' %}">Logout</a></li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Welcome, {{user.username}}</a>
                        </li>
                        {% else %}
                        <li><a class="nav-link" href="{% url 'bac_app:login' %}">Login</a></li>
                        {% endif %}
                      </ul> 
                    </li>   
                  
                  </ul>
                  <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                  </form>
                </div>
              </div>
            </div>
          </nav>

    </div>
    <script src="{% static 'bac_app/js/bootstrap.bundle.min.js' %}" ></script>
    {% block content %}
        <div class="da">
          <div class="container">
            <h1>Base</h1>
            <a class="nav-link" href="#">Welcome, {{user.username}}</a>
          </div>
        </div>
        
    {% endblock content %}
   
</body>
</html>

templates/bac_app/home.html
{% extends "bac_app/base.html" %}
{% block content %}
  <h1>home</h1>
{% endblock %}

templates/bac_app/login.html
{% extends "bac_app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="da">
    <div class="container">
     <form method="POST">
         {% csrf_token %}
         {{ login_form|crispy }}
         <button type="submit" class="btn btn-primary">login</button>
     </form>
     <p><span>you must have a accont to create an accont <a href="{% url 'bac_app:register' %}">Here..</a></span></p>
    </div>
</div>
  
{% endblock content %}

templates/bac_app/register.html
{% extends "bac_app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="da">
    <div class="container">
     <form method="POST">
         {% csrf_token %}
         {{ register_form|crispy }}
         <button type="submit" class="btn btn-primary">Registed</button>
     </form>
    </div>
</div>
  
{% endblock content %}